# Generated by Django 6.0 on 2026-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
