# Generated by Django 6.0 on 2026-01-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Categories',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'FrenchFries'), ('DESERT', 'Dessert'), ('BREVERAGES', 'Breveages')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
