# Generated by Django 6.0 on 2026-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_fooditems_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Categories',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'FrenchFries'), ('DESERT', 'Dessert'), ('BREVERAGES', 'Breveages'), ('BIRYANI', 'Biryani')], max_length=100),
        ),
    ]
