# Generated by Django 6.0 on 2026-01-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_fooditems_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
